name: Backend CI/CD

on:
  push:
    branches: [dev]
    paths:
      - 'backend/**'
  pull_request:
    branches: [dev]
    paths:
      - 'backend/**'
  workflow_dispatch:

env:
  REGISTRY: docker.io
  IMAGE_NAME: opeyemi-prac-backend

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push backend image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: ${{ secrets.REGISTRY }}/dream-vacation-backend:${{ github.sha }}
