name: Deploy on AWS EC2 Instance

on:
  push:
    branches: [ dev ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/dream-vacation-app:latest

      - name: Deploy to EC2
        run: |
          set -e
          echo "Copying files to EC2..."
          scp -o StrictHostKeyChecking=no -i ${{ secrets.EC2_SSH_KEY }} ./docker-compose.yml ubuntu@${{ secrets.EC2_PUBLIC_IP }}:/home/ubuntu/
          scp -o StrictHostKeyChecking=no -i ${{ secrets.EC2_SSH_KEY }} ./.env ubuntu@${{ secrets.EC2_PUBLIC_IP }}:/home/ubuntu/  # if applicable

          echo "Running Docker Compose on EC2..."
          ssh -o StrictHostKeyChecking=no -i ${{ secrets.EC2_SSH_KEY }} ubuntu@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
            cd /home/ubuntu
            docker-compose down
            docker-compose pull
            docker-compose up -d
            echo "Deployment complete."
EOF
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}