name: Deploy on AWS EC2 Instance

on:
  push:
    branches: [ dev ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/dream-vacation-app:latest

      - name: Deploy to EC2
        run: |
          set -e
          echo "Creating SSH key file..."
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/ec2-key.pem
          chmod 600 ~/.ssh/ec2-key.pem

          echo "Copying docker-compose.yml to EC2..."
          scp -o StrictHostKeyChecking=no -i ~/.ssh/ec2-key.pem \
            docker-compose.yml ubuntu@${{ secrets.EC2_PUBLIC_IP }}:/home/ubuntu/

          echo "Copying .env file to EC2 (if applicable)..."
          scp -o StrictHostKeyChecking=no -i ~/.ssh/ec2-key.pem \
            .env ubuntu@${{ secrets.EC2_PUBLIC_IP }}:/home/ubuntu/ || echo ".env file not found locally, skipping..."

          echo "Connecting to EC2 and deploying with Docker Compose..."
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/ec2-key.pem ubuntu@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
            cd /home/ubuntu
            echo "Stopping and removing old containers..."
            docker-compose down --remove-orphans
            echo "Pulling latest Docker image..."
            docker-compose pull
            echo "Starting containers in detached mode..."
            docker-compose up -d
            echo "✅ Deployment complete!"
