name: Deploy on AWS EC2 Instance

on:
  push:
    branches: [dev]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/dream-vacation-app:latest

      - name: Deploy to EC2
        run: |
          set -e

          echo "Creating SSH key..."
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/ec2-key.pem
          chmod 600 ~/.ssh/ec2-key.pem

          echo "Copying docker-compose.yml to EC2..."
          scp -o StrictHostKeyChecking=no -i ~/.ssh/ec2-key.pem \
            docker-compose.yml ubuntu@${{ secrets.EC2_HOST }}:/home/ubuntu/

          echo "Copying app source code to EC2..."
          scp -o StrictHostKeyChecking=no -i ~/.ssh/ec2-key.pem \
            -r . ubuntu@${{ secrets.EC2_HOST }}:/home/ubuntu/app/

          echo "Connecting to EC2 and deploying app..."
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/ec2-key.pem ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
            cd /home/ubuntu
            sudo docker-compose down --remove-orphans
            sudo docker-compose pull
            sudo docker-compose up -d
            echo "✅ App deployed successfully!"

