name: frontend CI/CD

on:
  push:
    branches: [dev]
    paths:
      - 'frontend/**'
  pull_request:
    branches: [dev]
    paths:
      - 'frontend/**'
  workflow_dispatch:

env:
  REGISTRY: docker.io
  IMAGE_NAME: opeyemi-prac-frontend

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Log in Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      
      - name: Build and push frontend Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: |
             docker.io/${{ secrets.DOCKER_USERNAME }}/dream-vacation-frontend:${{ github.sha }}